services:
  MYSQL:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: alaa
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"

  gestion-station-ski-backend:
    image: elgharbi/SkyLine:latest
    ports:
      - "8089:8089"
    depends_on:
      - MYSQL
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_SERVER_PORT: 8089
      SPRING_JPA_PROPERTIES_HIPERNATE_DIABLACT : org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update